include $(SRC_RT)/myOS/kernel/mem/Makefile
include $(SRC_RT)/myOS/kernel/task_sched/Makefile

KERNEL_OBJS = output/myOS/kernel/tick.o \
	      output/myOS/kernel/wallClock.o \
		  output/myOS/kernel/task.o \
	      $(MEM_OBJS)\
		  $(SCHED_OBJS)
